language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: reapresstestv2
  on:
    repo: Cvaniak/ReapressTestV2
script:
- echo "skipping tests"
env:
  global:
    secure: TovUGvRpugaV3mtWqC/yqKCr6SFYOwj/c2N1irpwtj5e5W84DrV8JgZRnE93rTf00X1tz45d0xg4giNq4vEWvncXpHnb6w4u2UFdxaC2Z1/Pins3wiyOhT3yVTEyGV2SDALWcIPKHsh88LTARrzxMUJ1fHESKRMOYIt7a8Zs/HbaJnq2Dr97Ryu0Y9GTGLweADgGTbX9IRQ0D7moLDbT5l39PTewjErvsbRMwOoy0pZ3q5uQrd3Z3SKvWM6YqaRv4+1E/Lku4BdZgkaKZrHJYVIEj5PiESmwy66YHQ4R2UWID+55aTahy4Zj8b2TRiQR5oCDUQ//K0oO458ZaFdxZeAPaWiagnpdfVnw8puCX2sS9hmJtq7P6fAe9NBEmTlF5w8eIM/7d1nKE8RMy9W/7zz0ViqXxxHyR/QiB6ANmTGjLspuZ9Ey5MK9Rlc3W9B3fV+4uQMkPWQ5TVfQmlRMjs6FpD0btZPTtZToDpoDyrrxRU0b8C1TwotmfAy2m+YZKdjqvJluAO4lVuh/3hObHjYHHNI3PHqC3wn9Asq0ui90C4MFbbdZGoHzl49ulZLjIFXIj71t4eKYgh6Zfgtn+42YmZ7r+3ySqJazcA9n5mkDXhYSQn8Obom6opCdWeWdzaqGtCz7Qr9DchEd1ovrLmQFhLhx21nb+KefbMPrWfI=
