language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "M6ImK+bmjig+NrOW1wkho+UgHWLtMw0sCAouJQAkOTwiZxkWhK8Mq1aHxIQal0eDR+YrqCHW2q0Hz6aBuQmBUSc3NAF7/2DNvqbvwX5IIZMtHcSBszEH3tfzZqsc/8UxJosarvRx7WtxAPq0FmtiCmtH2vnYk5rmcRUAFY5EvE2cjknHD/yVNAuH/NGnBYhwwBiU/JpcFr2gpJFqItpn7qrGyR2T8t/GiAS1Q6a7t0Yb2g6ut3er+EX7AlIwaWH5WwHNOsU2uspJ9cekIbiQ9hFk/ZDAjCRm1JZdkY/DGUdlHiSvk0LujKToWXgBo/RIyFl86QIv0uSpBVydpzL5jmYnWBvyR1netvzX/jwq21vr5Fuwz+YpGUxBL5xVmrBQzpecLO7ZUkZJgxEzIqD9/l+XqF7RiLMXGDvdO1sEvO4qv0ivYk7u+JXq+51CdDPzcqDev6ofH74JaBNgjnpSNB3LyJXMf+LHnuHNtsYlnF2gm+j4x8grWo95PSCyss+XZ8hfAyeLiFLC8bUO9/QPdrATOjboEDBqq2prZCc0VzG9fbBOfq5mMNJll5Lc76GXQkn09t9HtwIcTkm7bqzGWC1/4zK3/cICak1fepkksd6WiNDhBeD8jtsKkGwM9xuc7UQbpyClyUk0poxHDLddHSLYWqqamFPccaZgzNM7KWc="
    app: reapresstestv2
  on:
    repo: Cvaniak/ReapressTestV2
script:
- echo "skipping tests"
