language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: iQ+5I2d7+1rU61Jj7nc6/utfuA4w+S/q2q/CXSIxed0X6Xt5elV2l96yqFaBQK+pfao3vdTDSUe8mu3Y3G/rie/XQCHD1ymc2TcYFufgSdHuMfbf1YFMQ/kz+1mV8kMfp7H+Jr+zXFPU2yaHgz9Vo6b0MTF1fW5F0IeFQLfKM0v3WeDu4JyGyrac78L8WgtoHwHcpJXIQ1yx+pbQlpOlZBQ/a8Dffw5tcsn20aALnF8JxIM6fW/FDHqv2/k31XkjXkUbb6sHQATT4E6IGDwpuOYRWsprFDtXkLqO+RGSVidn9lgf7TCkf6Z35cvfSyIXF0ELvTfK7pY75PMovjIdr2ExZbN5vUUiHlDLvqDylv+bieSyCOLXkZd2taeuHb7V/odPZ5L96VpqMmYtt1u92tATtDmOLyRXNbsyyKmKkhVY0AiROUfahT99sZg02SrH0xUQNMKaBSmlbtH9ejT8EEJTOOuiWxffm1PgBIcqeLrZBFkyBvg8yjaZ8HXzmiM5IWAZw2ByJK4HogiT8MZXsNmlC79Q6ZOpX0S1hRJmu5vn2OrzRDvG5rg4IxxbmxSl3c2SiU5dfXauS0Hig95P5rOJcW4yxVuRU5LnK8OITyqEw26ICFHSxmrxGSStpwAL2YgUrM9TW2So8KVsRnTI/7VkhaapPIrKREcezvH8nCk=
  app: ReapressTestV2
  on:
    repo: Cvaniak/ReapressTestV2
script:
- echo "skipping tests "
