language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "fbOrTmsJZX/GdQKHVkHpL0Ye1f7ybs8u11ww9PAN27s7yYZLYvaUO6aC0Ed9gsbmroGtXTZooQIfU7eOCXpESV77tLTrRpuTk9qlHfxEzYWbFOC+tK4oI2t7XqasSSI+Th2FNowQdGj1HMOMgNt4mm/Kr0/GNo6gf5JV9Q7/W1XqltaVBBOLSGRgEIUWAFLxdX9NwavtQOA6V5hpmMyN6K4WdZfpA1PsZdWusW0e98DJyxSYaoSvIlZ2g1GjyYYmk/Z9b8Zn9K8ChmRDzNqcohmEPrOYACqoHwaoDIaquwU7NUa1WmYp12vzfnKYY79BE81RFFK68Ym8f7Y6OJq0U3+HuUvHxwniipZ0TAK4BGQj+/Bz9HNYsKwEZ4OHmJ5tq7jwL+q01PrVJM7BJ3bs+Y7s5/VTg3U2AcXUoMt0p8+aVMnhukc5KaYmcMRhfmCpJ4LWbYxej/pk/KwjBYoUqK6HjKK3wHqXvcsirW6X2LenLmkuY/GuX1L0qmc63itmIQxC0NXGcXWBFDLAMZXsSUDGVNKp6zC8zUvzxgpVp6ipQKsBeJMHUA/HOum5CNq4qm0R+HHrGcWn8FZ9FG2gF/B7IQvxI/foijll9HFUONObSksrXXXjIjJG7wGmlC8VKyjB6KrQuQFgbJiNMkc7nXIu9Tjw5K/41/xywW1X5Nk="
  app: reapresstestv2
  on:
    repo: Cvaniak/ReapressTestV2
script:
- echo "skipping tests"
